// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepoPattern2.Ef;

namespace RelativesData.Ef.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220328110211_AddRelativeTable")]
    partial class AddRelativeTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RelativesData.Ef.Models.Relative", b =>
                {
                    b.Property<int>("RelativeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("LastChange")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("SapNumber");

                    b.Property<string>("SourceDate")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("isEmployee");

                    b.HasKey("RelativeId");

                    b.ToTable("Relatives");
                });
#pragma warning restore 612, 618
        }
    }
}
